notifications:
  email: false

language: c

addons:
  apt:
    packages:
      - tcc # Install Tiny C compiler.

before_script:
  - tcc -version

script:
  - make CC=tcc && ./tarino
  - make CC=gcc && ./tarino
