notifications:
  email: false

language: c

addons:
  apt:
    packages:
      - tcc # Install Tiny C compiler.

before_script:
  - tcc -version

script:
  - make && ./tarino

after_script:
  - make CC=gcc && ./tarino
